<?php
	require_once('./core/functions/class_wtw-initsession.php');
	require_once('./core/functions/class_wtwadmin.php');
	require_once('./core/functions/class_wtwadminmenu.php');
	require_once('./core/functions/class_wtwmenus.php');
	require_once('./core/functions/class_wtwpluginloader.php');
	require_once('./core/functions/class_wtwplugins.php');
	global $wtw;
	global $wtwadmin;
	global $wtwadminmenu;
	global $wtwmenus;
	global $wtwpluginloader;
	$wtwadminmenu->preloadAdminMenu();
	$wtwadminmenu->preloadAdminSubMenu();
	$wtwpluginloader->getAllPlugins($wtw->contentpath,1); 
echo "<!DOCTYPE html>";
echo "<html lang='en' xml:lang='en' xmlns='http://www.w3.org/1999/xhtml' xmlns:fb='http://ogp.me/ns/fb#'>";
echo "<head>";
	echo $wtw->loadMetaData(); 
	echo $wtwadmin->loadCSSAdminData();
	echo $wtw->loadInitJSData(); 
	echo $wtwadmin->loadJSAdminData(); 
echo "</head>";
echo "<body>";
	echo $wtwadminmenu->getAdminMenuLayout();
	echo $wtw->loadMainElements();
	echo $wtwadmin->loadMainElementsAdmin();
	echo $wtw->loadHiddenFields();
	echo $wtwadmin->loadHiddenFieldsAdmin(); 
	echo $wtwmenus->getMainMenu();
	echo $wtwmenus->getSettingsMenu();
	echo $wtwmenus->getProfileMenu();
	echo $wtwmenus->getBrowseMenu('wtw_menuhelp','Help Menu');
	echo $wtwmenus->getAvatarMenu();
	echo $wtwmenus->getOptionalAnimations();
	echo $wtwmenus->getControlsMenu();
	echo $wtwmenus->getMovementMenu();
	echo $wtwmenus->getGraphicsMenu();
	echo $wtwmenus->getShadowsMenu();
	echo $wtwmenus->getMicMenu();
	echo $wtwmenus->getContentRatingMenu();
	echo $wtwmenus->getFeedbackMenu();
	echo $wtwmenus->getMenuForms();
	echo $wtwadmin->loadFullPageFormAdmin(); 
echo "</body>";
echo "</html>";