{
	"type":"BadRequestError",
	"status":400,
	"message":"Bad Request",
	"data":{
		"body":[
			{
				"instancePath":"",
				"schemaPath":"#/required",
				"keyword":"required",
				"params":{
					"missingProperty":"data"
				},
				"message":"must have required property \'data\'",
				"schema":["data"],
				"parentSchema":{
					"additionalProperties":false,
					"type":"object",
					"properties":{
						"data":{
							"anyOf":[
								{
									"additionalProperties":false,
									"type":"object",
									"properties":{
										"applicationId":{
											"format":"object-id",
											"type":"string"
										},
										"requestToken":{
											"type":"boolean"
										}
									},
									"required":[
										"applicationId"
									]
								},
								{
									"additionalProperties":false,
									"type":"object",
									"properties":{
										"appName":{
											"type":"string"
										},
										"requestToken":{
											"type":"boolean"
										}
									},
									"required":[
										"appName"
									]
								}
							]
						}
					},
					"required":["data"]
				},
				"data":{}
			}
		]
	}
}